package com.serverless.dynamodb;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

@DynamoDBTable(tableName = "PLACEHOLDER_COVIDSCREENING_TABLE_NAME")
public class CovidScreening {

    // get the table name from env. var. set in serverless.yml
    private static final String COVIDSCREENING_TABLE_NAME = System.getenv("COVIDSCREENING_TABLE_NAME");

    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;

    private Logger logger = Logger.getLogger(this.getClass());

    private String id;
    private String name;
    private String phone;
    private String date;
    private List<QuestionAndAnswer> questionAndAnswers;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "phone")
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @DynamoDBAttribute(attributeName = "date")
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @DynamoDBAttribute(attributeName = "questionAndAnswers")
    public List<QuestionAndAnswer> getQuestionAndAnswers() {
        return questionAndAnswers;
    }

    public void setQuestionAndAnswers(List<QuestionAndAnswer> questionAndAnswers) {
        this.questionAndAnswers = questionAndAnswers;
    }

    public CovidScreening() {
        // build the mapper config
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
            .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(COVIDSCREENING_TABLE_NAME))
            .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        this.client = this.db_adapter.getDbClient();
        // create the mapper with config
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }

    public String toString() {
        return String.format("CovidScreening [id=%s, name=%s, phone=%s, date=%s]", this.id, this.name, this.phone, this.date);
    }

    // methods
    public Boolean ifTableExists() {
        return this.client.describeTable(COVIDSCREENING_TABLE_NAME).getTable().getTableStatus().equals("ACTIVE");
    }

    public List<CovidScreening> list() throws IOException {
      DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
      List<CovidScreening> results = this.mapper.scan(CovidScreening.class, scanExp);
      for (CovidScreening p : results) {
        logger.info("CovidScreening - list(): " + p.toString());
      }
      return results;
    }

    public CovidScreening get(String id) throws IOException {
        CovidScreening covidScreening = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<CovidScreening> queryExp = new DynamoDBQueryExpression<CovidScreening>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<CovidScreening> result = this.mapper.query(CovidScreening.class, queryExp);
        if (result.size() > 0) {
          covidScreening = result.get(0);
          logger.info("CovidScreening - get(): covidScreening - " + covidScreening.toString());
        } else {
          logger.info("CovidScreening - get(): covidScreening - Not Found.");
        }
        return covidScreening;
    }

    public void save(CovidScreening covidScreening) throws IOException {
        logger.info("CovidScreening - save(): " + covidScreening.toString());
        this.mapper.save(covidScreening);
    }

    public Boolean delete(String id) throws IOException {
        CovidScreening covidScreening = null;

        // get covidScreening if exists
        covidScreening = get(id);
        if (covidScreening != null) {
          logger.info("CovidScreening - delete(): " + covidScreening.toString());
          this.mapper.delete(covidScreening);
        } else {
          logger.info("CovidScreening - delete(): covidScreening - does not exist.");
          return false;
        }
        return true;
    }

}
